<jsp:useBean id="javaP" scope="request" type="cn.yunsenlin.web.base.dto.sigar.JavaProperty"/>
<jsp:useBean id="cpu" scope="request" type="java.util.ArrayList"/>
<jsp:useBean id="memory" scope="request" type="cn.yunsenlin.web.base.dto.sigar.Memory"/>
<jsp:useBean id="os" scope="request" type="cn.yunsenlin.web.base.dto.sigar.Os"/>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<html>
<head>
    <title>系统监视器</title>
</head>
<body>
<h3>系统信息</h3>
<ul>
    <li>
        <h4>用户名</h4>
        <p>${javaP.userName}</p>
    </li>
    <li>
        <h4>计算机名</h4>
        <p>${javaP.computerName}</p>
    </li>
    <li>
        <h4>计算机域名</h4>
        <p>${javaP.userDomain}</p>
    </li>
    <li>
        <h4>本地ip地址</h4>
        <p>${javaP.ip}</p>
    </li>
    <li>
        <h4>本地主机名</h4>
        <p>${javaP.addr_getHostName}</p>
    </li>
    <li>
        <h4>JVM可以使用的总内存</h4>
        <p>${javaP.r_totalMemory}</p>
    </li>
    <li>
        <h4>JVM可以使用的剩余内存</h4>
        <p>${javaP.r_freeMemory}</p>
    </li>
    <li>
        <h4>JVM可以使用的处理器个数</h4>
        <p>${javaP.r_availableProcessors}</p>
    </li>
    <li>
        <h4>Java的运行环境版本</h4>
        <p>${javaP.java_version}</p>
    </li>
    <li><h4>Java的运行环境供应商</h4>
        <p>${javaP.java_vendor}</p>
    </li>
    <li><h4>Java供应商的URL</h4>
        <p>${javaP.java_vendor_url}</p>
    </li>
    <li><h4>Java的安装路径</h4>
        <p>${javaP.java_home}</p>
    </li>
    <li><h4>Java的虚拟机规范版本</h4>
        <p>${javaP.java_vm_specification_version}</p>
    </li>
    <li><h4>Java的虚拟机规范供应商</h4>
        <p>${javaP.java_vm_specification_vendor}</p>
    </li>
    <li><h4>Java的虚拟机规范名称</h4>
        <p>${javaP.java_vm_specification_name}</p>
    </li>
    <li><h4>Java的虚拟机实现版本</h4>
        <p>${javaP.java_vm_version}</p>
    </li>
    <li><h4>Java的虚拟机实现供应商</h4>
        <p>${javaP.java_vm_vendor}</p>
    </li>
    <li><h4>Java的虚拟机实现名称</h4>
        <p>${javaP.java_vm_name}</p>
    </li>
    <li><h4>Java运行时环境规范版本</h4>
        <p>${javaP.java_specification_version}</p>
    </li>
    <li><h4>Java运行时环境规范供应商</h4>
        <p>${javaP.java_specification_vender}</p>
    </li>
    <li><h4>Java运行时环境规范名称</h4>
        <p>${javaP.java_specification_name}</p>
    </li>
    <li><h4>Java的类格式版本号</h4>
        <p>${javaP.java_class_version}</p>
    </li>
    <li><h4>Java的类路径</h4>
        <p>${javaP.java_class_path}</p>
    </li>
    <li><h4>加载库时搜索的路径列表</h4>
        <p>${javaP.java_library_path}</p>
    </li>
    <li><h4>默认的临时文件路径</h4>
        <p>${javaP.java_io_tmpdir}</p>
    </li>
    <li><h4>一个或多个扩展目录的路径</h4>
        <p>${javaP.java_ext_dirs}</p>
    </li>
    <li><h4>操作系统的名称</h4>
        <p>${javaP.os_name}</p>
    </li>
    <li><h4>操作系统的构架</h4>
        <p>${javaP.os_arch}</p>
    </li>
    <li><h4>操作系统的版本</h4>
        <p>${javaP.os_version}</p>
    </li>
    <li><h4>文件分隔符</h4>
        <p>${javaP.file_separator}</p>
    </li>
    <li><h4>路径分隔符</h4>
        <p>${javaP.path_separator}</p>
    </li>
    <li><h4>行分隔符</h4>
        <p>${javaP.line_separator}</p>
    </li>
    <li><h4>用户的账户名称</h4>
        <p>${javaP.user_name}</p>
    </li>
    <li><h4>用户的主目录</h4>
        <p>${javaP.user_home}</p>
    </li>
    <li><h4>用户的当前工作目录</h4>
        <p>${javaP.user_dir}</p>
    </li>
</ul>
<h3>内存信息</h3>
<ul>
    <li>
        <h4>内存总量</h4>
        <p>${memory.total}KB</p>
    </li>
    <li>
        <h4>当前内存使用量</h4>
        <p>${memory.used}KB</p>
    </li>
    <li>
        <h4>当前内存剩余量</h4>
        <p>${memory.free}KB</p>
    </li>
    <li>
        <h4>交换区总量</h4>
        <p>${memory.swapTotal}KB</p>
    </li>
    <li>
        <h4>当前交换区使用量</h4>
        <p>${memory.swapUsed}KB</p>
    </li>
    <li>
        <h4>当前交换区剩余量</h4>
        <p>${memory.swapFree}KB</p>
    </li>
</ul>
<h3>CPU信息</h3>
<c:forEach var="cpuItem" items="${cpu}" varStatus="cpuVar">
    <h4>${cpuVar.index+1}号处理器</h4>
    <ul>
        <li>
            <h4>CPU的总量MHz</h4>
            <p>${cpuItem.mhz}</p>
        </li>
        <li>
            <h4>CPU生产商</h4>
            <p>${cpuItem.vendor}</p>
        </li>
        <li>
            <h4>CPU类别</h4>
            <p>${cpuItem.model}</p>
        </li>
        <li>
            <h4>CPU缓存数量</h4>
            <p>${cpuItem.cacheSize}</p>
        </li>
        <li>
            <h4>CPU用户使用率</h4>
            <p>${cpuItem.cpuPerc.user}</p>
        </li>
        <li>
            <h4>CPU系统使用率</h4>
            <p>${cpuItem.cpuPerc.sys}</p>
        </li>
        <li>
            <h4>CPU当前等待率</h4>
            <p>${cpuItem.cpuPerc.wait}</p>
        </li>
        <li>
            <h4>CPU当前错误率</h4>
            <p>${cpuItem.cpuPerc.nice}</p>
        </li>
        <li>
            <h4>CPU当前空闲率</h4>
            <p>${cpuItem.cpuPerc.idle}</p>
        </li>
        <li>
            <h4>CPU总的使用率</h4>
            <p>${cpuItem.cpuPerc.combined}</p>
        </li>
    </ul>
</c:forEach>
<h3>操作系统</h3>
<ul>
    <li>
        <h4>操作系统</h4>
        <p>${os.arch}</p>
    </li>
    <li>
        <h4>操作系统CpuEndian</h4>
        <p>${os.cpuEndian}</p>
    </li>
    <li>
        <h4>操作系统DataModel</h4>
        <p>${os.dataModel}</p>
    </li>
    <li>
        <h4>操作系统的描述</h4>
        <p>${os.description}</p>
    </li>
    <li>
        <h4>操作系统类型</h4>
        <p>${os.name},${os.patchLevel}</p>
    </li>
    <li>
        <h4>操作系统的卖主</h4>
        <p>${os.vendor}</p>
    </li>
    <li>
        <h4>操作系统的卖主名</h4>
        <p>${os.vendorCodeName}</p>
    </li>
    <li>
        <h4>操作系统名称</h4>
        <p>${os.vendorName}</p>
    </li>
    <li>
        <h4>操作系统卖主类型</h4>
        <p>${os.vendorVersion}</p>
    </li>
    <li>
        <h4>操作系统的版本号</h4>
        <p>${os.version}</p>
    </li>
</ul>
</body>
</html>
